name: Generate Maven Repository Index

on:
  push:
    branches: [ main ]
    paths:
      - 'releases/**'  # 只有当目录内容变化时才触发
      - 'snapshots/**'
      - 'plugins/**'
  workflow_dispatch:     # 允许手动触发

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录，可能需要用于版本比较
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Download Maven Indexer
      run: |
        # 下载最新版indexer-cli
        INDEXER_VERSION=$(curl -s https://repo.maven.apache.org/maven2/org/apache/maven/indexer/indexer-cli/maven-metadata.xml | grep -oP '(?<=<latest>)[^<]+')
        wget https://repo.maven.apache.org/maven2/org/apache/maven/indexer/indexer-cli/${INDEXER_VERSION}/indexer-cli-${INDEXER_VERSION}.jar -O indexer.jar
    
    - name: Generate index
      run: |
        # 创建索引目录
        mkdir -p releases/.index
        mkdir -p snapshots/.index
        mkdir -p plugins/.index
        
        # 生成索引
        java -jar indexer.jar \
          --scan ./releases \
          --index ./releases/.index \
          --repoId github-releases-repo \
          --repoUrl https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/repository
        java -jar indexer.jar \
          --scan ./snapshots \
          --index ./snapshots/.index \
          --repoId github-snapshots-repo \
          --repoUrl https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/repository
        java -jar indexer.jar \
          --scan ./plugins \
          --index ./plugins/.index \
          --repoId github-plugins-repo \
          --repoUrl https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/repository
        
        # 创建属性文件
        cat <<EOF > ./releases/.index/nexus-maven-repository-index.properties
        #Nexus Index Properties
        version=1
        incremental=false
        repositoryId=github-releases-repo
        timestamp=$(date +%s000)
        description=Maven repository hosted on GitHub
        EOF
        # 创建属性文件
        cat <<EOF > ./snapshots/.index/nexus-maven-repository-index.properties
        #Nexus Index Properties
        version=1
        incremental=false
        repositoryId=github-snapshots-repo
        timestamp=$(date +%s000)
        description=Maven repository hosted on GitHub
        EOF
        # 创建属性文件
        cat <<EOF > ./plugins/.index/nexus-maven-repository-index.properties
        #Nexus Index Properties
        version=1
        incremental=false
        repositoryId=github-plugins-repo
        timestamp=$(date +%s000)
        description=Maven repository hosted on GitHub
        EOF
        
        # 显示生成的索引大小
        du -sh ./releases/.index
        du -sh ./snapshots/.index
        du -sh ./plugins/.indez
    
    - name: Commit and push index
      run: |
        # 配置git用户
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 检查是否有索引文件变化
        git add releases/.index
        git add snapshots/.index
        git add plugins/.index
        if ! git diff --cached --quiet; then
          git commit -m "Update Maven repository index [skip ci]"
          git push
        else
          echo "No changes in index files"
        fi
