name: Build and Publish

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - 'releases/**'
      - 'snapshots/**'
      - 'plugins/**'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate Repository Index
        run: |
          node generate-repo-data.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git add index-cache.json
          git diff --quiet && git diff --staged --quiet || git commit -m "自动更新仓库索引"
          git push
